rule all:
    input:
        "./de/control_example_de_cts.csv"

rule control_atlas:
    input: 
        "example_control.csv"
    params: 
        wd = ".", name = "control_example"
    output: 
        "control_example.rds"
    shell: 
        "Rscript build_control_atlas.R {params.wd} {input} {params.name}"

rule transfer_atlas:
    input: 
        "control_example.rds", "example_disease.csv"
    params: 
        wd = ".", name = "disease_example"
    output: 
        "disease_example.rds"
    shell: 
        "Rscript transfer_cell_type.R {params.wd} {input} {params.name}"

rule data_analysis:
    input: 
        "disease_example.rds"
    params: 
        wd = ".", name1 = "control_example", name2 = "disease_example"
    output: 
        "./de/control_example_de_cts.csv"
    shell: 
        "Rscript run_analysis.R {params.wd} {params.name1} {params.name2}"
